### ISSUE TITLE
/api/order/query文档响应参数与实际响应参数不一致

### ISSUE THREAD

**Issue by ZPOMI** [MeizuAppCenter/MzAppCenterSdkServerDemo#1]
文档中的cp_trace_no、trace_no在实际响应中分别为cp_trade_no、trade_no,望统一修正下

**Comment by shawnlinboy** [comment]
@1160135186 PTAL.

**Comment by shawnlinboy** [comment]
Already fixed at https://github.com/MeizuAppCenter/MzAppCenterSdkServerDemo/commit/c4e3aafc4c72bc3fbd6372fc5ec4ea0abc39cd1f, thx.
