### ISSUE TITLE
Suggestion: change the Content-Type header in pay callback request

### ISSUE THREAD

**Issue by bitholic** [MeizuAppCenter/MzAppCenterSdkServerDemo#2]
The Content-Type of the pay callback request is currently set to `plain / text`, which is inconvenient to parse. It would be better to set it to `application/x-www-form-urlencoded`.

**Comment by TalkLessDoMore555** [comment]
it was defined when that project was first set up, now that some parterner have already  joined in.so it is hard to change callback request api.Maybe you could see demos we provide to parse request info, we hope if would be helpful for you.
